/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/pXdxE81PTjg
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'/

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Input } from "@/components/ui/input"

export function Conversation() {
  return (
    <div className="flex flex-col h-screen bg-muted">
      <header className="bg-background border-b px-4 py-3 flex items-center gap-4 shrink-0">
        <div className="flex-1">
          <h2 className="text-lg font-semibold">Support Ticket #12345</h2>
          <div className="text-sm text-muted-foreground">Pending</div>
        </div>
        <Button variant="ghost" size="icon" className="rounded-full">
          <DotIcon className="h-5 w-5" />
          <span className="sr-only">More options</span>
        </Button>
      </header>
      <div className="flex-1 overflow-y-auto p-4">
        <div className="grid gap-4">
          <div className="flex items-start gap-4">
            <Avatar className="shrink-0">
              <AvatarImage src="/placeholder-user.jpg" alt="Client" />
              <AvatarFallback>C</AvatarFallback>
            </Avatar>
            <div className="grid gap-2 max-w-[75%]">
              <div className="bg-card rounded-lg p-3 text-sm">
                <p>Hi, I'm having trouble with the payment process. Can you please help me?</p>
              </div>
              <div className="text-xs text-muted-foreground">10:30 AM</div>
            </div>
          </div>
          <div className="flex items-start gap-4 justify-end">
            <div className="grid gap-2 max-w-[75%]">
              <div className="bg-primary rounded-lg p-3 text-sm text-primary-foreground">
                <p>Sure, let me take a look. Can you please provide more details about the issue you're facing?</p>
              </div>
              <div className="text-xs text-muted-foreground">10:32 AM</div>
            </div>
            <Avatar className="shrink-0">
              <AvatarImage src="/placeholder-user.jpg" alt="Admin" />
              <AvatarFallback>A</AvatarFallback>
            </Avatar>
          </div>
          <div className="flex items-start gap-4">
            <Avatar className="shrink-0">
              <AvatarImage src="/placeholder-user.jpg" alt="Client" />
              <AvatarFallback>C</AvatarFallback>
            </Avatar>
            <div className="grid gap-2 max-w-[75%]">
              <div className="bg-card rounded-lg p-3 text-sm">
                <p>
                  I'm trying to make a payment, but the website keeps giving me an error message. Can you please check
                  what's going on?
                </p>
              </div>
              <div className="text-xs text-muted-foreground">10:35 AM</div>
            </div>
          </div>
          <div className="flex items-start gap-4 justify-end">
            <div className="grid gap-2 max-w-[75%]">
              <div className="bg-primary rounded-lg p-3 text-sm text-primary-foreground">
                <p>
                  Okay, let me investigate the issue. In the meantime, could you please try clearing your browser cache
                  and cookies? That might help resolve the problem.
                </p>
              </div>
              <div className="text-xs text-muted-foreground">10:37 AM</div>
            </div>
            <Avatar className="shrink-0">
              <AvatarImage src="/placeholder-user.jpg" alt="Admin" />
              <AvatarFallback>A</AvatarFallback>
            </Avatar>
          </div>
          <div className="flex items-start gap-4">
            <Avatar className="shrink-0">
              <AvatarImage src="/placeholder-user.jpg" alt="Client" />
              <AvatarFallback>C</AvatarFallback>
            </Avatar>
            <div className="grid gap-2 max-w-[75%]">
              <div className="bg-card rounded-lg p-3 text-sm">
                <p>Okay, I've tried that and it seems to have worked. Thank you for your help!</p>
              </div>
              <div className="text-xs text-muted-foreground">10:40 AM</div>
            </div>
          </div>
        </div>
      </div>
      <div className="bg-background border-t px-4 py-3 flex items-center gap-4 shrink-0">
        <Input
          type="text"
          placeholder="Type your message..."
          className="flex-1 rounded-full bg-muted px-4 py-2 text-sm"
        />
        <Button variant="secondary" size="icon" className="rounded-full">
          <PaperclipIcon className="h-5 w-5" />
          <span className="sr-only">Attach file</span>
        </Button>
        <Button variant="secondary" size="icon" className="rounded-full">
          <SendIcon className="h-5 w-5" />
          <span className="sr-only">Send message</span>
        </Button>
        <Button variant="destructive" size="icon" className="rounded-full">
          <XIcon className="h-5 w-5" />
          <span className="sr-only">Close ticket</span>
        </Button>
      </div>
    </div>
  )
}

function DotIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12.1" cy="12.1" r="1" />
    </svg>
  )
}


function PaperclipIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21.44 11.05-9.19 9.19a6 6 0 0 1-8.49-8.49l8.57-8.57A4 4 0 1 1 18 8.84l-8.59 8.57a2 2 0 0 1-2.83-2.83l8.49-8.48" />
    </svg>
  )
}


function SendIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
